version: '3.8'

services:
  backend:
    build: ./giftlink-backend
    ports:
      - "3060:3060"
    environment:
      - JWT_SECRET=your_secret
      - MONGO_URL=mongodb://mongo:27017/giftdb
    depends_on:
      - mongo

  frontend:
    build: ./giftlink-frontend
    ports:
      - "9000:9000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3060

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
